### PR TITLE
Feat: dark mode button

### PR DESCRIPTION
**Pull request by kelilipan**
Add dark mode toggle
image

### CODE REVIEW

**Comment by kelilipan** [comment]
idk, pnpm detect my node version as "15.x" but I'm using "14.xLTS" so I'm disabling "strict". also, I'm disabling some eslint rules because error

can you please check before merge this?

**Comment by agallio** [comment]
Sure! Will do. Checking

**Comment by agallio** [comment]
Can you improve this not-so-readable text too @svspicious?

image

**Comment by kelilipan** [comment]
done
image

**Comment by agallio** [comment]
Please fix this z-index issue @svspicious

image

**Comment by kelilipan** [comment]
hmm, the button already on the top of another component, right?
i don't see any issue

**Comment by agallio** [comment]
Hmmm, so I think it's an opacity issue. Could you check so the white border doesn't overlap with the button?

**Comment by kelilipan** [comment]
ahhh, ok changing the color

**Comment by kelilipan** [comment]
is this enough?
2yUupSv69o

i think the button will conflict with #16 layout
but we'll figure out later

**Comment by agallio** [comment]
It's still showing the white border from the HospitalCard component 🤔

**Comment by kelilipan** [comment]
dang, it's from `active` button. CSS is hard wkw
it should be fixed now

**Comment by agallio** [comment]
Wkwkwkwk dang. 🤣 
Okay thanks, lemme check

**Comment by agallio** [comment]
@svspicious please check if there's any issues for the button after rebased with the main branch

**Comment by kelilipan** [comment]
i know it will overlap on `map` page.
any suggestion? or should we disable this on map page?
image

**Comment by kelilipan** [comment]
it becomes unreadable since the style is not inherited from chakra-ui
image

**Comment by agallio** [comment]
Hmmm can we disable the Chakra-UI dark mode on map page?

**Comment by kelilipan** [comment]
unfortunately, we can't.
well, I will refactor map page using all chakra-ui

**Comment by agallio** [comment]
Wait. I think we can force the page to use light mode only. [See this](https://chakra-ui.com/docs/features/color-mode#forcing-a-specific-mode)

**Comment by kelilipan** [comment]
https://chakra-ui.com/docs/features/color-mode#forcing-a-specific-mode only works on chakra component
i simply add `color="black"` and it works

**Comment by kelilipan** [comment]
UPDATE:
image

Screenshot 2021-07-09 091944
Screenshot 2021-07-09 091931

image

**Comment by kelilipan** [comment]
i'm sorry wrong executing rebase command :( should I repoen this PR?

**Comment by agallio** [comment]
Yes please @svspicious. Thank you 🙇🏻

**Pull request closed without merging**
